services:
  - type: web
    name: profel-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 5000
      - key: FLASK_DEBUG
        value: "false"
      - key: GROQ_API_KEY
        sync: false

  - type: static
    name: profel-frontend
    env: node
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: REACT_APP_API_URL
        value: https://profel.onrender.com/api
      - key: REACT_APP_ENV
        value: production